version: "3.8"

services:
  server:
    # image: 'nginx:stable-alpine'
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated

  server2:
    # image: 'nginx:stable-alpine'
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - "8001:80"
    volumes:
      - ./src2:/var/www/html
      - ./nginx2/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php2
      - mysql
  php2:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src2:/var/www/html:delegated

  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    env_file:
      - ./env/mysql.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    env_file:
      - ./env/mysql.env
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "3400:80"
    depends_on:
      - mysql

  # composer:
  #   build:
  #     context: ./dockerfiles
  #     dockerfile: composer.dockerfile
  #   volumes:
  #     - ./src:/var/www/html

  composer:
    image: composer
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    command: "composer install"

  composer2:
    image: composer
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src2:/var/www/html
    working_dir: /var/www/html
    command: "composer install"

  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
  npm:
    image: node:latest
    command: sh -c "npm install && npm run build"
    volumes:
      - ./src:/app
